
.. _core-developers-team:

These are the current contributors of `mdreg`:

.. raw:: html

   <div class="team-member">
     <a href="https://github.com/plaresmedima" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/6051075?v=4"
             loading="lazy"
             alt="Avatar picture of @plaresmedima"
           />
        </div>
        Steven Sourbron
     </a>
     <div class="team-member-handle">@plaresmedima</div>
   </div>

   
   <div class="team-member">
     <a href="https://github.com/JoaoPeriquito" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/48806417?v=4"
             loading="lazy"
             alt="Avatar picture of @JoaoPeriquito"
           />
        </div>
        João Periquito
     </a>
     <div class="team-member-handle">@JoaoPeriquito</div>
   </div>

   <div class="team-member">
     <a href="https://github.com/KanishkaS" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/42036722?v=4"
             loading="lazy"
             alt="Avatar picture of @KanishkaS"
           />
        </div>
        Kanishka Sharma
     </a>
     <div class="team-member-handle">@KanishkaS</div>
   </div>

   <div class="team-member">
     <a href="https://github.com/JSousa-UoL" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/53518061?v=4"
             loading="lazy"
             alt="Avatar picture of @JSousa-UoL"
           />
        </div>
        Jo&atildeo Almeida e Sousa
     </a>
     <div class="team-member-handle">@JSousa-UoL</div>
   </div>

   <div class="team-member">
     <a href="https://github.com/lauracbell" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/46763125?v=4"
             loading="lazy"
             alt="Avatar picture of @lauracbell"
           />
        </div>
        Laura Bell
     </a>
     <div class="team-member-handle">@lauracbell</div>
   </div>