
.. _maintainers-team:

These are the current maintainers of `mdreg`:

.. raw:: html

         <div class="team-member">
     <a href="https://github.com/EShalom" class="team-member-name">
        <div class="team-member-photo">
           <img
             src="https://avatars.githubusercontent.com/u/79933818?v=4"
             loading="lazy"
             alt="Avatar picture of @EShalom"
           />
        </div>
        Eve Shalom
     </a>
     <div class="team-member-handle">@EShalom</div>
   </div>